### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by fopina** [datamachine/twx#3]
It seems pip installation is not working, not even from repository directly:

```
(env) skmac:izclibot fopina$ python --version
Python 3.4.3
(env) skmac:izclibot fopina$ pip --version
pip 7.0.3 from /Users/fopina/Documents/djangoapps/izclibot/env/lib/python3.4/site-packages (python 3.4)
(env) skmac:izclibot fopina$ pip install git+https://github.com/datamachine/twx
Collecting git+https://github.com/datamachine/twx
  Cloning https://github.com/datamachine/twx to /var/folders/2_/jkg8hd9s4qd74528tk_rxvpm0000gn/T/pip-9v7ej75w-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/2_/jkg8hd9s4qd74528tk_rxvpm0000gn/T/pip-9v7ej75w-build/setup.py", line 37, in <module>
        raise Exception('Unkown target: {}', sys.argv)
    Exception: ('Unkown target: {}', ['-c', 'egg_info', '--egg-base', 'pip-egg-info'])

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/folders/2_/jkg8hd9s4qd74528tk_rxvpm0000gn/T/pip-9v7ej75w-build
```

**Comment by xlopo** [comment]
It looks like a local check that was supposed to only run on my system was running on pip installations as well. I removed that check, you may installing the latest version now.

**Comment by fopina** [comment]
Confirmed, thanks.
